server:
  port: 8085

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message
      registration-mail: registration_mail
  datasource:
    url: jdbc:postgresql://localhost:5432/history
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
  profiles:
    active: development

token: 7165285757:AAFzAYKrWE0jgUphwFGfStDLsDCkWpMU-Zc


logging:
  level:
    root: INFO

# Используем переменную среды JAVA_TOOL_OPTIONS
java:
  tool:
    options: ${JAVA_TOOL_OPTIONS1}

